# Generated by Django 6.0.1 on 2026-02-01 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('gov_code', models.CharField(blank=True, max_length=100, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('license_document', models.FileField(blank=True, null=True, upload_to='licenses/')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_id', models.CharField(max_length=66, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=100)),
                ('expiry', models.DateField()),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication_app.manufacturer')),
            ],
        ),
    ]
