# Generated by Django 6.0.1 on 2026-02-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='tx_hash',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
    ]
