# Generated by Django 6.0.1 on 2026-02-01 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0002_medicine_tx_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='drug_id',
        ),
    ]
